version: '3.8'
services:
  client:
    build: ./client
    networks:
      - pake-net
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - pake-net
networks:
  pake-net:
    driver: bridge
