version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - pake-net
    ports:
      - "3000:3000" 
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - pake-net
    ports:
      - "8080:8080"
    volumes:
      - ./protocols:/go/src/protocols
      - ./benchmarks:/go/src/benchmarks

networks:
  pake-net:
    driver: bridge